services:
  - type: web
    name: 9devy-llc
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WORDPRESS_DB_HOST
        value: 173.29.195.50:4403
      - key: WORDPRESS_DB_NAME
        value: 9devy_llc
      - key: WORDPRESS_DB_USER
        value: 9devy_user
      - key: WORDPRESS_DB_PASSWORD
        value: DevySecurePass123!

