services:
  - type: web
    name: 9devy-site
    env: docker
    repo: https://github.com/The9Devy/9devy-site
    branch: main
    plan: free
    envVars:
      - key: WORDPRESS_DB_HOST
        fromService:
          type: pserv
          name: 9devy-db
      - key: WORDPRESS_DB_USER
        value: devy
      - key: WORDPRESS_DB_PASSWORD
        value: devypass123
      - key: WORDPRESS_DB_NAME
        value: devydb
